name: soor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  form_field_validator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.4.0
  build_runner: ^2.4.8

flutter:
  fonts:
      - family: SF-Arabic
        fonts:
          - asset: assets/fonts/sf-arabic/SFArabic-Regular.ttf
  uses-material-design: true
  assets:
    - assets/images/soor.png
    - assets/images/buildings.png
    - assets/images/someoneholdingphone.png
    - assets/images/saudimap.png